name: ai4medicine-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - notebook
  - jupyterlab
  - ipywidgets
  - numpy
  - pandas
  - scikit-learn
  - shap
  - matplotlib
  - seaborn
  - stackview
  - pydicom
  - tqdm
  - pip:
    - bia-bob
    - torch
    - torchvision
    - torchmetrics
    - torchsummary
    - torchstain
    - cmcrameri
    - openslide-python
    - openslide-bin
    - openai
    - openai-agents
    - PyMuPDF
    - tiktoken
    - faiss-cpu
    - ddgs

variables:
  BLABLADOR_API_KEY: "my_api_key"
