name: ai4medicine-env
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - notebook
  - jupyterlab
  - ipywidgets
  - scikit-learn
  - pip:
    - bia-bob

variables:
  BLABLADOR_API_KEY: "my_api_key"