name: ai4medicine-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - notebook
  - jupyterlab
  - ipywidgets
  - numpy
  - pandas
  - scikit-learn
  - shap
  - matplotlib
  - seaborn
  - stackview
  - pydicom
  - pip:
    - bia-bob

variables:
  BLABLADOR_API_KEY: "my_api_key"
