name: ai4medicine-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - notebook
  - jupyterlab
  - ipywidgets
  - numpy
  - scikit-learn
  - pip:
    - bia-bob
    - shap
    - stackview

variables:
  BLABLADOR_API_KEY: "my_api_key"